Repository dodona-edu/judge-html, pull requests merged in 2021-11, with the labels that each got.

#185 Increase test coverage for validators/checks
  tests/helpers.py
  tests/html_files/css_1.html
  tests/test_validators/test_checks.py
  tests/test_validators/test_element.py
  tests/test_validators/test_element_container.py
  tests/test_validators/test_testsuite.py
  utils/color_converter.py
  utils/evaluation_module.py
  utils/html_navigation.py
  validators/checks.py
Labels: enhancement, draft

#142 Line numbers
  codecov.yaml
  exceptions/double_char_exceptions.py
  exceptions/double_char_exceptions.pyi
  exceptions/html_exceptions.py
  exceptions/html_exceptions.pyi
  exceptions/structure_exceptions.py
  exceptions/structure_exceptions.pyi
  exceptions/utils.py
  exceptions/utils.pyi
  tests/helpers.py
  tests/html_files/css_1.html
  tests/test_validators/test_checks.py
  tests/test_validators/test_element.py
  tests/test_validators/test_element_container.py
  tests/test_validators/test_testsuite.py
  utils/color_converter.py
  utils/evaluation_module.py
  utils/html_navigation.py
  validators/checks.py
  validators/css_validator.py
  validators/double_chars_validator.py
  validators/double_chars_validator.pyi
  validators/html_validator.py
  validators/structure_validator.py
  validators/structure_validator.pyi
Labels: enhancement, draft

#184 Compare similarity
  dodona/translator.py
  dodona/translator.pyi
  requirements.txt
  validators/checks.py
  validators/structure_validator.py
  validators/structure_validator.pyi
Labels: enhancement

#198 Catch error for empty submissions
  tests/test_utils/test_html_checks.py
  utils/html_checks.py
  validators/checks.py
  validators/structure_validator.py
Labels: bug

#199 Add check for minimal HTML template
  docs/pages/default-suites.md
  tests/helpers.py
  validators/checks.py
  validators/checks.pyi
Labels: documentation, enhancement

#201 Any order for shorthand components
  docs/pages/element-class.md
  tests/html_files/css_1.html
  tests/test_validators/test_element.py
  validators/checks.py
  validators/checks.pyi
Labels: documentation, enhancement

#200 Fix Annotation error
  dodona/dodona_command.py
  dodona/dodona_command.pyi
  validators/checks.py
Labels: bug

#195 css style check with css selector (no html doc)
  docs/pages/testsuite-class.md
  tests/test_validators/test_css_validator.py
  validators/checks.py
  validators/css_validator.py
  validators/css_validator.pyi
Labels: enhancement
